# Generated by Django 4.2.30 on 2026-08-30 20:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=60)),
                ('message', models.TextField()),
                ('language_code', models.CharField(blank=True, max_length=12)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('closed', 'Closed'), ('spam', 'Spam')], db_index=True, default='new', max_length=16)),
                ('email_sent', models.BooleanField(default=False)),
                ('internal_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='HomeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('admin_name', models.CharField(max_length=140)),
                ('background', models.CharField(choices=[('white', 'White'), ('gold', 'Gold'), ('light', 'Light grey'), ('dark', 'Black')], default='white', max_length=10)),
            ],
            options={
                'ordering': ('sort_order', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('code', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^[a-z]{2,3}(?:-[A-Z]{2})?$', 'Use a code such as en, nl, or en-GB.')])),
                ('name', models.CharField(max_length=80)),
                ('native_name', models.CharField(max_length=80)),
                ('is_default', models.BooleanField(default=False)),
                ('flag', models.FileField(blank=True, upload_to='languages/flags/')),
                ('legacy_flag_path', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('title', models.CharField(max_length=180)),
                ('kind', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document')], default='image', max_length=12)),
                ('file', models.FileField(blank=True, upload_to='website/assets/')),
                ('legacy_path', models.CharField(blank=True, help_text='Existing path inside src/assets.', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('sort_order', 'title'),
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('kind', models.CharField(choices=[('service', 'Service'), ('project', 'Project'), ('standard', 'Standard page')], db_index=True, max_length=12)),
                ('slug', models.SlugField(max_length=120)),
                ('card_image', models.FileField(blank=True, upload_to='website/page-cards/')),
                ('legacy_card_image_path', models.CharField(blank=True, max_length=300)),
                ('show_on_homepage', models.BooleanField(default=True)),
                ('show_in_navigation', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card_media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_cards', to='website.mediaasset')),
            ],
            options={
                'ordering': ('kind', 'sort_order', 'title_key__key'),
            },
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('admin_name', models.CharField(help_text='Internal name shown in the admin.', max_length=140)),
                ('layout', models.CharField(choices=[('text_left', 'Text left / media right'), ('text_right', 'Media left / text right'), ('full', 'Full width')], default='text_left', max_length=16)),
                ('background', models.CharField(choices=[('white', 'White'), ('gold', 'Gold'), ('light', 'Light grey')], default='white', max_length=10)),
                ('image', models.FileField(blank=True, upload_to='website/sections/')),
                ('legacy_image_path', models.CharField(blank=True, max_length=300)),
                ('video', models.FileField(blank=True, upload_to='website/sections/video/')),
                ('legacy_video_path', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'ordering': ('sort_order', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='VARTEC', max_length=80)),
                ('logo', models.FileField(blank=True, upload_to='website/branding/')),
                ('legacy_logo_path', models.CharField(default='image/logo.png', max_length=255)),
                ('primary_colour', models.CharField(default='#FFC107', max_length=7)),
                ('contact_email', models.EmailField(default='info@vartec.global', max_length=254)),
                ('uk_phone', models.CharField(default='+44 800 772 0316', max_length=40)),
                ('nl_phone', models.CharField(default='+31 6 3834 2809', max_length=40)),
                ('notification_email', models.EmailField(blank=True, max_length=254)),
                ('hero_enabled', models.BooleanField(default=True)),
                ('about_enabled', models.BooleanField(default=True)),
                ('services_enabled', models.BooleanField(default=True)),
                ('projects_enabled', models.BooleanField(default=True)),
                ('contact_enabled', models.BooleanField(default=True)),
                ('footer_enabled', models.BooleanField(default=True)),
                ('video_enabled', models.BooleanField(default=True)),
                ('video', models.FileField(blank=True, upload_to='website/video/')),
                ('legacy_video_path', models.CharField(default='video/finalmerge.mp4', max_length=255)),
                ('default_seo_title', models.CharField(default='Solar EPC, Battery Storage & O&M in the UK | VARTEC', max_length=180)),
                ('default_seo_description', models.TextField(default='VARTEC delivers solar EPC, battery storage, carports, floating solar and operations and maintenance services across the UK and Europe.')),
                ('organisation_schema_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Site settings',
            },
        ),
        migrations.CreateModel(
            name='TextKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=120, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9_]+$', 'Use uppercase letters, numbers, and underscores.')])),
                ('default_text', models.TextField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('key',),
            },
        ),
        migrations.CreateModel(
            name='TextTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='website.language')),
                ('text_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='website.textkey')),
            ],
            options={
                'ordering': ('language__sort_order', 'language__code'),
            },
        ),
        migrations.CreateModel(
            name='SectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('item_type', models.CharField(choices=[('paragraph', 'Paragraph'), ('bullet', 'Bullet'), ('numbered', 'Numbered item'), ('subheading', 'Subheading')], default='paragraph', max_length=12)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='website.pagesection')),
                ('text_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.textkey')),
            ],
            options={
                'ordering': ('sort_order', 'pk'),
            },
        ),
        migrations.AddField(
            model_name='pagesection',
            name='body_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_bodies', to='website.textkey'),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.mediaasset'),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='website.page'),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='title_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_titles', to='website.textkey'),
        ),
        migrations.AddField(
            model_name='page',
            name='intro_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='page_intros', to='website.textkey'),
        ),
        migrations.AddField(
            model_name='page',
            name='seo_description_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_seo_descriptions', to='website.textkey'),
        ),
        migrations.AddField(
            model_name='page',
            name='seo_title_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_seo_titles', to='website.textkey'),
        ),
        migrations.AddField(
            model_name='page',
            name='title_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='page_titles', to='website.textkey'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='alt_text_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.textkey'),
        ),
        migrations.CreateModel(
            name='HomeFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='website.homeblock')),
                ('body_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_feature_bodies', to='website.textkey')),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.mediaasset')),
                ('title_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_feature_titles', to='website.textkey')),
            ],
            options={
                'ordering': ('sort_order', 'pk'),
            },
        ),
        migrations.AddField(
            model_name='homeblock',
            name='intro_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_block_intros', to='website.textkey'),
        ),
        migrations.AddField(
            model_name='homeblock',
            name='title_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_block_titles', to='website.textkey'),
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('title', models.CharField(max_length=120)),
                ('image', models.FileField(blank=True, upload_to='website/hero/')),
                ('legacy_image_path', models.CharField(blank=True, max_length=255)),
                ('alt_text_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.textkey')),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.mediaasset')),
            ],
            options={
                'ordering': ('sort_order', 'pk'),
            },
        ),
        migrations.AddConstraint(
            model_name='texttranslation',
            constraint=models.UniqueConstraint(fields=('text_key', 'language'), name='unique_text_translation'),
        ),
        migrations.AddConstraint(
            model_name='page',
            constraint=models.UniqueConstraint(fields=('kind', 'slug'), name='unique_page_kind_slug'),
        ),
    ]
